config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :todos
  get 'home/index'
  # root 'home#index'
  # root 'todos#index'
  root 'users#sign_in'
  get 'home/help'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/todo.rb
class Todo < ApplicationRecord
    belongs_to:user
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
  
  def Help

    @article_votes="testControl"
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [ :index, :show]
  before_action :correct_user, only:[:edit,:update,:destroy]
  # GET /todos or /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    # @todo = Todo.new
    @todo = current_user.todos.build
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    # @todo = Todo.new(todo_params)
    @todo = current_user.todos.build(todo_params)
    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @todo=current_user.todos.find_by(id: params[:id])
    redirect_to todos_path, notice: "Not authorized to edit todo" if @todo.nil? 

  end   





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:task_name, :task_created_at, :task_editted_at, :task_done_by, :task_desc, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'ToDo', 
    root_path,class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       
      <li class="nav-item">
      <% if user_signed_in? %>
        </li>
        <li class="nav-item">
        <%# <%= link_to 'Show Task', todos_path,class:"nav-link"%> 
       
          
        </li>
    
        <%= link_to 'Add Tasks', new_todo_path,class:"nav-link"  %>
       
        <li class="nav-item">
        <%= link_to 'Edit Profile', edit_user_registration_path,class:"nav-link"  %>
       
          
        </li>
        <li class="nav-item">
       
        <%= link_to 'Help', home_help_path,class:"nav-link"  %>
          
        </li>
        </li>
        <li class="nav-item">
        <%= link_to 'Sign out', destroy_user_session_path,method: :delete, class:"nav-link"  %>
       
          
        </li>
        <% else %>
          
        </li>
        <li class="nav-item">
        <%= link_to 'Sign Up', new_user_registration_path,class:"nav-link"  %>
       
          
        </li>
        <li class="nav-item">
        <%= link_to 'Sign In', new_user_session_path,class:"nav-link"  %>
        <% end %>
          
       
        
       
      </ul>
      <% if user_signed_in? %>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <% end %>
    </div>
  </div>
</nav>

app/views/home/help.html.erb
<h1>Help</h1>

app/views/home/index.html.erb
<h1>SMATR TODO List</h1>
<p>Demo ruby </p>
<p>Basic Practise </p>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">

  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>ToDo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  </head>
  <body>
    <%= render'home/header' %>
    <div class="container">
    <br/>
    <% if notice%>
     <%= render 'layouts/alert'  %>
     <% end  %>


      <%= yield %>
     </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :task_name,class: "form-label " %>
    <%= form.text_field :task_name,class:"form-control"  %>
  </div>

  <div class="field ">
    <%= form.label :task_created_at,class: "form-label"  %>
    <%= form.datetime_select :task_created_at,class:"form-select" %>
  </div>

  <div class="field">
    <%= form.label :task_editted_at ,class: "form-label" %>
    <%= form.datetime_select :task_editted_at,class:"form-select" %>
  </div>

  <div class="field">
    <%= form.label :task_done_by,class: "form-label"  %>
    <%= form.datetime_select :task_done_by,class:"form-select" %>
  </div>

  <div class="field mb-3">
    <%= form.label :task_desc,class: "form-label"  %>
    <%= form.text_field :task_desc,class:"form-control" %>
  </div>
 <div class="field mb-3">
    
    <%= form.number_field :user_id,id: :todo_user_id,class:"form-control",value: current_user.id,type: :hidden%>
  </div>
 
  <div class="actions">
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>
<br/>
<%= render 'form', todo: @todo %>
<br/>
<%= link_to 'Show', @todo ,class:"btn btn-secondary"%> 
<%= link_to 'Delete', @todo, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger" %>
<%= link_to 'Back', todos_path ,class:"btn btn-dark" %>

app/views/todos/index.html.erb
<%if user_signed_in? %>
  <h1>Todos</h1>

  <table class="table table table-striped table-bordered table-hover">
  <thead class="table-dark">
      <tr>
        <%# <th>User ID</th> %>
        <th>Task name</th>
        <th>Task created at</th>
        <th>Last editted at</th>
        <th>Task need to be done by</th>
        <th>Task description </th>
        
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @todos.each do |todo| %>
        <% if todo.user==current_user %>
        <tr>
          <%# <td><%= todo.user_id</td> %> 
          <td><%= link_to todo.task_name, todo , class: " text-decoration-none"%></td>
          <td><%= todo.task_created_at %></td>
          <td><%= todo.task_editted_at %></td>
          <td><%= todo.task_done_by %></td>
          <td><%= todo.task_desc %></td>
       
          <%# <td><%= link_to 'Edit', edit_todo_path(todo),class:"btn btn-info" </td> %>
          <td><%= link_to 'Delete', todo, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-outline-danger btn-sm" %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Todo', new_todo_path, class: "btn btn-secondary" %>
<%else%>

<h1>SMATR TODO List</h1>


<%end%>

app/views/todos/new.html.erb
<h1>Add a Task</h1>
<br/>
<%= render 'form', todo: @todo %>
<br/>
<%= link_to 'Back', todos_path , class:"btn btn-primary"%>

app/views/todos/show.html.erb
<div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold"><%= @todo.task_name %></h1>
        <p class="col-md-8 fs-4"> <%= @todo.task_desc %></p>
        <p class="col-md-8 fs-4">Create at: <%= @todo.task_created_at %></p>
        <p class="col-md-8 fs-4">Last Modified: <%= @todo.task_editted_at %></p>
        <p class="col-md-8 fs-4">Needs to be done by: <%= @todo.task_done_by %></p>
        <%= link_to 'Edit', edit_todo_path(@todo), class: "btn btn-secondary" %> 
<%= link_to 'Delete', @todo, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger" %>

        <%= link_to 'Back', todos_path, class: "btn btn-dark" %>
      </div>
    </div>